actions:
  abortActions: []
  emailNotifications: []
  setVariableActions:
  - description: null
    exitCodes: null
    notificationOption: Operation Failure
    notifyOnEarlyFinish: false
    notifyOnLateFinish: false
    notifyOnLateStart: false
    notifyOnProjectedLate: false
    status: Success
    sysId: 01028ac38e7b443b8368cc8628caefd4
    variableName: output_holder
    variableScope: Top Level Parent
    variableValue: ${_replaceAll('${__outputLinesByRegex('STDOUT', '.*File:.*')}',
      '.*File:?', ' ')}
  snmpNotifications: []
  systemOperations: []
agent: Hoffenheim
agentCluster: null
agentClusterVar: null
agentVar: null
authenticatePeer: false
avgRunTime: 2
avgRunTimeDisplay: 2 Seconds
broadcastCluster: null
broadcastClusterVar: null
codepage: -- None --
command: GET
compress: 'NO'
cpDuration: null
cpDurationUnit: Minutes
createop: REPLACE
credentials: null
credentialsVar: null
customField1:
  label: Requestor Name
  value: null
customField2:
  label: docu link
  value: null
efDayConstraint: None
efDuration: 00:00:00:00
efEnabled: false
efNthAmount: 5
efOffsetDuration: null
efOffsetDurationUnit: Minutes
efOffsetPercentage: 0
efOffsetType: Percentage
efTime: 00:00
efType: Time
encrypt: 'NO'
exclusiveTasks: []
exclusiveWithSelf: false
executionRestriction: None
exitCodeOutput: null
exitCodeProcessing: Success Exitcode Range
exitCodeText: null
exitCodes: '0'
exportReleaseLevel: 7.3.0.0
exportTable: ops_task_ftp
firstRun: 2022-11-23 17:52:32 +0100
formOrScript: Form
format: Text
ftpSubcommands: null
holdResources: false
jobcard: null
lastRun: 2023-03-07 13:05:49 +0100
lastRunTime: 3
lastRunTimeDisplay: 3 Seconds
lfDayConstraint: None
lfDuration: 00:00:00:00
lfEnabled: false
lfNthAmount: 5
lfOffsetDuration: null
lfOffsetDurationUnit: Minutes
lfOffsetPercentage: 0
lfOffsetType: Percentage
lfTime: 00:00
lfType: Time
localFilename: '"${aduserlist}"'
logLevel: Inherited
lsDayConstraint: None
lsDuration: 00:00:00:00
lsEnabled: false
lsNthAmount: 5
lsTime: 00:00
lsType: Time
maxRunTime: 3
maxRunTimeDisplay: 3 Seconds
minRunTime: 0
minRunTimeDisplay: 0 Seconds
move: false
name: KM-UDM-Test - Copy
nft: false
notes: []
opswiseGroups:
- KM-Job-as-Code
outputType: STDOUT
primaryBroker: null
primaryBrokerChoice: Utility Agent
primaryBrokerRef: null
primaryCluster: null
primaryClusterRef: null
primaryCredVar: null
primaryCredentials: null
primaryFilesys: -- None --
primaryOpenOptions: null
remoteCredVar: null
remoteCredentials: null
remoteFilename: '"${aduserlist}"'
remoteServer: null
resPriority: 10
resolveNameImmediately: false
restrictionPeriod: None
restrictionPeriodAfterDate: null
restrictionPeriodAfterTime: null
restrictionPeriodBeforeDate: null
restrictionPeriodBeforeTime: null
restrictionPeriodDateList: []
retainSysIds: true
retryExitCodes: null
retryIndefinitely: false
retryInterval: 60
retryMaximum: 0
retrySuppressFailure: false
runCount: 4
runTime: 6
runtimeDir: null
script: null
secondaryBroker: null
secondaryBrokerChoice: Agent
secondaryBrokerRef: Frankfurt
secondaryCluster: null
secondaryClusterRef: null
secondaryCredVar: null
secondaryCredentials: Frankfurt_UDM
secondaryFilesys: -- None --
secondaryOpenOptions: null
serverType: UDM
showProgress: false
startHeld: false
startHeldReason: null
summary: null
sysId: 79de4455047c47108233223ae7e39bff
timeZonePref: -- System Default --
transferDirection: PUT
transferMode: Passive
trimSpace: false
twDelayAmount: null
twDelayDuration: 00:00:00:00
twDelayType: None
twWaitAmount: null
twWaitDayConstraint: None
twWaitDuration: 00:00:00:00
twWaitTime: 00:00
twWaitType: None
twWorkflowOnly: -- System Default --
type: taskFtp
udmOperation: Copy
udmOptions: null
useRegex: false
userEstimatedDuration: null
variables:
- allowEmptyOption: false
  allowUnlistedOption: false
  description: null
  name: password
  options: []
  sysId: 251a846ae99d443ba2b7d7079360b5e5
  value: ${_credentialPwd('kmuc')}
- allowEmptyOption: false
  allowUnlistedOption: false
  description: null
  name: username
  options: []
  sysId: 2c51e28af1ff4df6980780b87e943cf8
  value: '${_credentialUser(''kmuc'')}


    '
verifyHostName: false
version: 5
virtualResources: []
