actions:
  abortActions: []
  emailNotifications: []
  setVariableActions: []
  snmpNotifications: []
  systemOperations: []
agent: Ansible
agentCluster: null
agentClusterVar: null
agentVar: null
avgRunTime: 7
avgRunTimeDisplay: 7 Seconds
broadcastCluster: null
broadcastClusterVar: null
chainDesc: null
chainId: null
commandGroup: Display
commandOptions: '-model_status any

  -selusername *

  -resolve_multi_model yes'
cpDuration: null
cpDurationUnit: Minutes
credentials: km-airflow-root
credentialsVar: null
customField1:
  label: Requestor Name
  value: null
customField2:
  label: docu link
  value: null
dataSource: null
defFile: null
definitionOrModel: USAP Definition File
definitionOrModelJobVar: USAP Definition File
dispAbapName: null
dispSapEventId: null
dispSapEventParm: null
dispVariant: null
efDayConstraint: None
efDuration: 00:00:00:00
efEnabled: false
efNthAmount: 5
efOffsetDuration: null
efOffsetDurationUnit: Minutes
efOffsetPercentage: 0
efOffsetType: Percentage
efTime: 00:00
efType: Time
environment: []
exclusiveTasks: []
exclusiveWithSelf: false
executionRestriction: None
exitCodeOutput: null
exitCodeProcessing: Success Exitcode Range
exitCodeText: null
exitCodes: '0'
exportReleaseLevel: 7.3.0.0
exportTable: ops_task_sap
firstRun: 2023-01-31 13:26:59 +0100
holdResources: false
immediate: true
infoPackage: null
infoPackageJobName: null
infoSource: null
jobId: null
jobLog: true
jobName: '*'
jobStatus: null
lastRun: 2023-01-31 14:46:25 +0100
lastRunTime: 4
lastRunTimeDisplay: 4 Seconds
lfDayConstraint: None
lfDuration: 00:00:00:00
lfEnabled: false
lfNthAmount: 5
lfOffsetDuration: null
lfOffsetDurationUnit: Minutes
lfOffsetPercentage: 0
lfOffsetType: Percentage
lfTime: 00:00
lfType: Time
logId: null
logLevel: Inherited
lsDayConstraint: None
lsDuration: 00:00:00:00
lsEnabled: false
lsNthAmount: 5
lsTime: 00:00
lsType: Time
maxRunTime: 9
maxRunTimeDisplay: 9 Seconds
minRunTime: 4
minRunTimeDisplay: 4 Seconds
name: 'KM-List-SAP-Jobs '
notes: []
opswiseGroups:
- Karthik Mohan
- KM-Job-as-Code
outputFailureOnly: false
outputReturnFile: null
outputReturnNline: '100'
outputReturnSline: '1'
outputReturnText: null
outputReturnType: OUTERR
outputType: STDOUT
pcRestart: false
printAppLog: true
printAppRc: true
purge: false
repositoryOrFilesys: Script
requestId: null
resPriority: 10
resolveNameImmediately: false
restrictionPeriod: None
restrictionPeriodAfterDate: null
restrictionPeriodAfterTime: null
restrictionPeriodBeforeDate: null
restrictionPeriodBeforeTime: null
restrictionPeriodDateList: []
retainSysIds: true
retryIndefinitely: false
retryInterval: 60
retryMaximum: 0
retrySuppressFailure: false
runCount: 3
runTime: 22
runtimeDir: null
sapCmProfileId: null
sapCmProfileType: null
sapCmXmlFile: null
sapCommandMask: null
sapConnection: SAP-MACHINE-TRAINING-CLIENT-001
sapConnectionVar: null
sapCred: KM-SAP-HOFF
sapCredVar: null
sapDispConfirmEvents: false
sapDispEventSelectState: New
sapDisplayCommand: Select
sapEventId: null
sapEventParm: null
sapFromDate: null
sapLang: null
sapPrinterName: null
sapToDate: null
script: null
sourceSystem: null
spoollist: true
start: false
startHeld: false
startHeldReason: null
stepNum: null
summary: null
sysId: 4361f459bda8477ab080cef04f907029
targetJobName: null
targetServer: null
targetVariantName: null
timeZonePref: -- System Default --
twDelayAmount: null
twDelayDuration: 00:00:00:00
twDelayType: None
twWaitAmount: null
twWaitDayConstraint: None
twWaitDuration: 00:00:00:00
twWaitTime: 00:00
twWaitType: None
twWorkflowOnly: -- System Default --
type: taskSap
useAppRc: false
userEstimatedDuration: null
variables:
- allowEmptyOption: false
  allowUnlistedOption: false
  description: null
  name: ABAP_NAME
  options: []
  sysId: 8beae58d01894db289ded5b522b37835
  value: ABAP_DOCU_list
- allowEmptyOption: false
  allowUnlistedOption: false
  description: null
  name: ABAP_VARIANT
  options: []
  sysId: 815241526f2a4490b271c33a11749cf2
  value: VAR_LIST_ALL
version: 11
virtualResources:
- amount: 10
  resource: only two commission run
  resourceVar: null
  sysId: a5ca632ee03a4b6aaeae4930ce5d6c34
wait: false
waitForOutput: false
