actions:
  abortActions: []
  emailNotifications: []
  setVariableActions: []
  snmpNotifications: []
  systemOperations: []
agent: Atlanta
agentCluster: null
agentClusterVar: null
agentVar: null
avgRunTime: 16
avgRunTimeDisplay: 16 Seconds
broadcastCluster: null
broadcastClusterVar: null
broker: 192.168.30.18
brokerChoice: Agent Hostname
brokerCred: as400 credentials
brokerCredVar: null
brokerRef: null
command: '"USBMJOB CMD(WRKACTJOB) JOB(CONSOLE) JOBD() JOBQ() JOBPTY(1) OUTQ() OUTPTY(1)
  PRTDEV()  POLL(1)"'
commandOptions: null
commandOrScript: Command
cpDuration: null
cpDurationUnit: Minutes
credentials: null
credentialsVar: null
customField1:
  label: Requestor Name
  value: null
customField2:
  label: docu link
  value: null
efDayConstraint: None
efDuration: 00:00:00:00
efEnabled: false
efNthAmount: 5
efOffsetDuration: null
efOffsetDurationUnit: Minutes
efOffsetPercentage: 0
efOffsetType: Percentage
efTime: 00:00
efType: Time
exclusiveTasks: []
exclusiveWithSelf: false
executionRestriction: None
exitCodeOutput: null
exitCodeProcessing: Success Exitcode Range
exitCodeText: null
exitCodes: '0'
exportReleaseLevel: 7.3.0.0
exportTable: ops_task_indesca
firstRun: 2022-06-21 09:49:35 +0200
holdResources: false
lastRun: 2022-11-25 16:00:30 +0100
lastRunTime: 25
lastRunTimeDisplay: 25 Seconds
lfDayConstraint: None
lfDuration: 00:00:00:00
lfEnabled: false
lfNthAmount: 5
lfOffsetDuration: null
lfOffsetDurationUnit: Minutes
lfOffsetPercentage: 0
lfOffsetType: Percentage
lfTime: 00:00
lfType: Time
logLevel: Inherited
lsDayConstraint: None
lsDuration: 00:00:00:00
lsEnabled: false
lsNthAmount: 5
lsTime: 00:00
lsType: Time
maxRunTime: 26
maxRunTimeDisplay: 26 Seconds
minRunTime: 7
minRunTimeDisplay: 7 Seconds
name: KM - iSeries (AS400) Example 1
notes: []
opswiseGroups:
- Karthik Mohan
- KM-Job-as-Code
outputFailureOnly: false
outputReturnFile: null
outputReturnNline: '100'
outputReturnSline: '1'
outputReturnText: null
outputReturnType: OUTERR
outputType: STDOUT
resPriority: 10
resolveNameImmediately: false
restrictionPeriod: None
restrictionPeriodAfterDate: null
restrictionPeriodAfterTime: null
restrictionPeriodBeforeDate: null
restrictionPeriodBeforeTime: null
restrictionPeriodDateList: []
retainSysIds: true
retryExitCodes: null
retryIndefinitely: false
retryInterval: 60
retryMaximum: 0
retrySuppressFailure: false
runCount: 6
runTime: 93
runtimeDir: null
script: null
scriptOptions: null
startHeld: false
startHeldReason: null
summary: null
sysId: a204954933d747b691e9fc3e7116054b
timeZonePref: -- System Default --
twDelayAmount: null
twDelayDuration: 00:00:00:00
twDelayType: None
twWaitAmount: null
twWaitDayConstraint: None
twWaitDuration: 00:00:00:00
twWaitTime: 00:00
twWaitType: None
twWorkflowOnly: -- System Default --
type: taskUcmd
userEstimatedDuration: null
variables: []
version: 4
virtualResources: []
waitForOutput: false
