actions:
  abortActions: []
  emailNotifications: []
  setVariableActions: []
  snmpNotifications: []
  systemOperations: []
agent: Kubernetes
agentCluster: null
agentClusterVar: null
agentVar: null
avgRunTime: 0
avgRunTimeDisplay: 0 Seconds
broadcastCluster: null
broadcastClusterVar: null
byPercentage: null
byScale: 1024
bySize: null
cpDuration: null
cpDurationUnit: Minutes
credentials: kubernetes
credentialsVar: null
customField1:
  label: Requestor Name
  value: null
customField2:
  label: docu link
  value: null
efDayConstraint: None
efDuration: 00:00:00:00
efEnabled: false
efNthAmount: 5
efOffsetDuration: null
efOffsetDurationUnit: Minutes
efOffsetPercentage: 0
efOffsetType: Percentage
efTime: 00:00
efType: Time
exclusiveTasks: []
exclusiveWithSelf: false
executionRestriction: None
exportReleaseLevel: 7.3.0.0
exportTable: ops_task_file_monitor
fileGroup: null
fileName: /home/karthik/bill_file/INP_Bill_Data3.dat
fileOwner: null
firstRun: 2021-06-23 10:03:14 +0200
fmtype: Created
holdResources: false
lastRun: 2021-06-23 11:25:30 +0200
lastRunTime: 0
lastRunTimeDisplay: 0 Seconds
lfDayConstraint: None
lfDuration: 00:00:00:00
lfEnabled: false
lfNthAmount: 5
lfOffsetDuration: null
lfOffsetDurationUnit: Minutes
lfOffsetPercentage: 0
lfOffsetType: Percentage
lfTime: 00:00
lfType: Time
logLevel: Inherited
lsDayConstraint: None
lsDuration: 00:00:00:00
lsEnabled: false
lsNthAmount: 5
lsTime: 00:00
lsType: Time
maxFiles: null
maxRunTime: 0
maxRunTimeDisplay: 0 Seconds
minFileScale: KB
minFileSize: null
minRunTime: 0
minRunTimeDisplay: 0 Seconds
name: KM-FILEMONITOR
notes: []
opswiseGroups:
- Karthik Mohan
- KM-Job-as-Code
recursive: false
resPriority: 10
resolveNameImmediately: false
restrictionPeriod: None
restrictionPeriodAfterDate: null
restrictionPeriodAfterTime: null
restrictionPeriodBeforeDate: null
restrictionPeriodBeforeTime: null
restrictionPeriodDateList: []
retainSysIds: true
runCount: 3
runTime: 0
scanForward: false
scanText: null
stableSeconds: null
startHeld: false
startHeldReason: null
summary: 'Check for new input files '
sysId: 59deae1b32f84aab855c7222c71411c3
timeZonePref: -- System Default --
toScale: 1024
toSize: null
triggerOnExist: true
twDelayAmount: null
twDelayDuration: 00:00:00:00
twDelayType: None
twWaitAmount: null
twWaitDayConstraint: None
twWaitDuration: 00:00:00:00
twWaitTime: 00:00
twWaitType: None
twWorkflowOnly: -- System Default --
type: taskFileMonitor
useRegex: false
userEstimatedDuration: null
variables: []
version: 6
virtualResources: []
