actions:
  abortActions: []
  emailNotifications: []
  setVariableActions: []
  snmpNotifications: []
  systemOperations: []
agent: Frankfurt
agentCluster: null
agentClusterVar: null
agentVar: null
broadcastCluster: null
broadcastClusterVar: null
byPercentage: null
byScale: 1024
bySize: null
cpDuration: null
cpDurationUnit: Minutes
credentials: Amsterdam-Ravi
credentialsVar: null
customField1:
  label: Requestor Name
  value: null
customField2:
  label: docu link
  value: null
efDayConstraint: None
efDuration: 00:00:00:00
efEnabled: false
efNthAmount: 5
efOffsetDuration: null
efOffsetDurationUnit: Minutes
efOffsetPercentage: 0
efOffsetType: Percentage
efTime: 00:00
efType: Time
exclusiveTasks: []
exclusiveWithSelf: false
executionRestriction: None
exportReleaseLevel: 7.3.0.0
exportTable: ops_task_file_monitor
fileGroup: null
fileName: /home/ravi/scripts/inp_file_karthik.txt
fileOwner: null
firstRun: ''
fmtype: Created
holdResources: false
lastRun: ''
lfDayConstraint: None
lfDuration: 00:00:00:00
lfEnabled: true
lfNthAmount: 5
lfOffsetDuration: null
lfOffsetDurationUnit: Minutes
lfOffsetPercentage: 0
lfOffsetType: Percentage
lfTime: 08:00
lfType: Time
logLevel: Inherited
lsDayConstraint: None
lsDuration: 00:00:00:00
lsEnabled: true
lsNthAmount: 5
lsTime: 07:00
lsType: Time
maxFiles: null
minFileScale: KB
minFileSize: null
name: KM-JaC-CHECK-BILLING-INPUT-FILES
notes: []
opswiseGroups:
- KM-Job-as-Code
recursive: false
resPriority: 10
resolveNameImmediately: false
restrictionPeriod: None
restrictionPeriodAfterDate: null
restrictionPeriodAfterTime: null
restrictionPeriodBeforeDate: null
restrictionPeriodBeforeTime: null
restrictionPeriodDateList: []
retainSysIds: true
runCount: 0
runTime: 0
scanForward: false
scanText: null
stableSeconds: null
startHeld: false
startHeldReason: null
summary: Check for billing input files
sysId: 7a85e78a64b84ec2a79776d0cc07e5ca
timeZonePref: -- System Default --
toScale: 1024
toSize: null
triggerOnExist: false
twDelayAmount: null
twDelayDuration: 00:00:00:00
twDelayType: None
twWaitAmount: null
twWaitDayConstraint: None
twWaitDuration: 00:00:00:00
twWaitTime: 00:00
twWaitType: None
twWorkflowOnly: -- System Default --
type: taskFileMonitor
useRegex: false
userEstimatedDuration: null
variables: []
version: 1
virtualResources: []
